### ISSUE TITLE
Remove code that removes duplicates from the neighborhood sampling C++ code

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#2597]
Current implementation of neighborhood sampling removes duplicates before returning the results.

After some discussion, we'd like to remove this from the algorithm and provide it as a separate callable function on the result.  This will allow for the caller to decide whether removing the duplicate edges is desired or not.

**Comment by alexbarghi-nv** [comment]
@ChuckHastings will this be resolved by #2751 ?

**Comment by ChuckHastings** [comment]
Partially.  How important is the "provide a separate callable function on the result"?

I've removed the call in #2751.  I still have the C++ low level implementation (it's ifdef'ed out), but I haven't added a publicly callable C++ function or C API that would use this function.  If it's critical I can look at adding them, if it's not critical I can create a separate issue for that and address it in 22.12.

**Comment by alexbarghi-nv** [comment]
Not important.  The only issue is that the new behavior (not removing duplicates) is technically correct, but will break some tests. I'll have to update those.

**Comment by alexbarghi-nv** [comment]
Or alternatively preserve the old behavior for 22.10.  I'll discuss with the libs team tomorrow.

**Comment by ChuckHastings** [comment]
Adding the call back into the code for PR #2751.  Since this would be a breaking change I will create a separate PR just for this change in release 22.12.
